### ISSUE TITLE
Still having trouble creating the Listener-node

### ISSUE THREAD

**Issue by lucasmhenrique** [timvandermeij/radio-tomography#4]
Hi Tim, I'm still have problem when try to make the Listener-node.

Now it look like the sdcc is woking properly. Before I was having trouble with SDCC, I changed the directory to a new path in the programs and now it seems to me that it is working.
However at the time of creating the Listener-node, I was having an error like "NOP" redefined " (You can see the erro). 

`ucas@lucas-VirtualBox:~/radio-tomography/software/listener-node$ make
/home/lucas/Install/sdcc/sdcc-3.8.0/bin/sdcc  -c -I/home/lucas/radio-tomography/software/listener-node/../../libraries/multi-spin-3.0/listener-node -I/home/lucas/radio-tomography/software/listener-node/../../libraries/cc-usb-firmware/source/components/usb/class_cdc -I/home/lucas/radio-tomography/software/listener-node/../../libraries/cc-usb-firmware/source/components/usb/library -I/home/lucas/radio-tomography/software/listener-node/../../libraries/cc-usb-firmware/source/components/common -I/home/lucas/radio-tomography/software/listener-node/../../libraries/cc-usb-firmware/source/components/common/cc8051 -I/home/lucas/radio-tomography/software/listener-node/../../libraries/cc-usb-firmware/source/components/targets/interface -I/home/lucas/radio-tomography/software/listener-node/../../libraries/cc-usb-firmware/source/components/targets/cc2531_dongle -I/home/lucas/radio-tomography/software/listener-node/../../libraries/cc-usb-firmware/source/components/utils -I/home/lucas/radio-tomography/software/listener-node/../../libraries/multi-spin-3.0/xpand2531 -I/home/lucas/radio-tomography/software/listener-node/../../libraries/cc-usb-firmware/source/components/radios/cc2530 -DNDEBUG -DBUF_SIZE=192 -DUSB_UART -Dchip=2531 --Werror --disable-warning 85 --disable-warning 84 --model-large --opt-code-size  /home/lucas/radio-tomography/software/listener-node/../../libraries/multi-spin-3.0/listener-node/main.c -o /home/lucas/radio-tomography/software/listener-node/../../libraries/multi-spin-3.0/listener-node/main.rel
In file includ```
ed from /home/lucas/radio-tomography/software/listener-node/../../libraries/cc-usb-firmware/source/components/targets/interface/hal_led.h:18,
                 from /home/lucas/radio-tomography/software/listener-node/../../libraries/multi-spin-3.0/listener-node/main.c:25:
/home/lucas/radio-tomography/software/listener-node/../../libraries/cc-usb-firmware/source/components/common/hal_types.h:148:1: error: "NOP" redefined
In file included from /usr/local/share/sdcc/include/mcs51/cc2530.h:33,
                 from /home/lucas/radio-tomography/software/listener-node/../../libraries/multi-spin-3.0/listener-node/main.c:22:
/usr/local/share/sdcc/include/mcs51/compiler.h:92:1: error: this is the location of the previous definition
make: *** [/home/lucas/radio-tomography/software/listener-node/../../libraries/multi-spin-3.0/listener-node/main.rel] Error 1`

Inside the  hal_types.h code I've added.
`#ifndef NOP
#define NOP __asm \
NOP \
__endasm; \

#endif`

Now I'm having this problem.

`/home/lucas/Install/sdcc/sdcc-3.8.0/bin/sdcc  -c -I/home/lucas/radio-tomography/software/listener-node/../../libraries/multi-spin-3.0/listener-node -I/home/lucas/radio-tomography/software/listener-node/../../libraries/cc-usb-firmware/source/components/usb/class_cdc -I/home/lucas/radio-tomography/software/listener-node/../../libraries/cc-usb-firmware/source/components/usb/library -I/home/lucas/radio-tomography/software/listener-node/../../libraries/cc-usb-firmware/source/components/common -I/home/lucas/radio-tomography/software/listener-node/../../libraries/cc-usb-firmware/source/components/common/cc8051 -I/home/lucas/radio-tomography/software/listener-node/../../libraries/cc-usb-firmware/source/components/targets/interface -I/home/lucas/radio-tomography/software/listener-node/../../libraries/cc-usb-firmware/source/components/targets/cc2531_dongle -I/home/lucas/radio-tomography/software/listener-node/../../libraries/cc-usb-firmware/source/components/utils -I/home/lucas/radio-tomography/software/listener-node/../../libraries/multi-spin-3.0/xpand2531 -I/home/lucas/radio-tomography/software/listener-node/../../libraries/cc-usb-firmware/source/components/radios/cc2530 -DNDEBUG -DBUF_SIZE=192 -DUSB_UART -Dchip=2531 --Werror --disable-warning 85 --disable-warning 84 --model-large --opt-code-size  /home/lucas/radio-tomography/software/listener-node/../../libraries/cc-usb-firmware/source/components/usb/library/cc2531/usb_interrupt.c -o /home/lucas/radio-tomography/software/listener-node/../../libraries/cc-usb-firmware/source/components/usb/library/cc2531/usb_interrupt.rel
/home/lucas/radio-tomography/software/listener-node/../../libraries/cc-usb-firmware/source/components/usb/library/cc2531/usb_interrupt.c:88: error 158: overflow in implicit constant conversion
make: *** [/home/lucas/radio-tomography/software/listener-node/../../libraries/cc-usb-firmware/source/components/usb/library/cc2531/usb_interrupt.rel] Error 1
lucas@lucas-VirtualBox:~/radio-tomography/software/listener-node$ `

By chance do you know if someone has used this toolchain successfully?

Could you tell me what version of linux you used to create it?

Sorry to bother you one more time.Any help will be very welcome.

Thank you very much.

**Comment by lucasmhenrique** [comment]
The code is stopping at this line. 

`86    if (P2IFG & P2IFG_DPIF) {
 87       // Resume interrupt detected on D+ line while in suspend
 88       P2IFG = ~P2IFG_DPIF;
`

**Comment by timvandermeij** [comment]
It looks like more modern versions of SDCC define `NOP` now (see https://github.com/svn2github/sdcc/blob/9c0aadedc773f031ae9547f56a00c3cf5cbd89b3/sdcc/device/include/mcs51/compiler.h#L92), so there should then be no more need for https://github.com/timvandermeij/radio-tomography/blame/master/libraries/cc-usb-firmware/source/components/common/hal_types.h#L148-L150.

I think the main issue for your compilation problems is that you're using SDCC 3.8.0, which is newer than the one I mentioned in the `README` file, namely SDCC 3.3.0. The newer version brings some improvements like the definition of `NOP`, but that means that the library code also needs to be adjusted to support SDCC 3.8.0, which hasn't been done since we only had SDCC 3.3.0 at the time. Therefore, the easiest way to compile is just to get a copy of SDCC 3.3.0 (either compile it from source or use a package manager), or alternatively you could go through the errors and update the library to support SDCC 3.8.0, but that will be more work.
